# Generated by Django 4.0.4 on 2022-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_image', models.ImageField(upload_to='')),
                ('posts_text', models.CharField(max_length=300)),
                ('posts_data_time', models.DateTimeField()),
                ('posts_title', models.CharField(max_length=50)),
            ],
        ),
    ]
